# Generated by Django 6.0.5 on 2026-09-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'car'), ('bike', 'bike')], max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('electric', 'electric')], max_length=30)),
                ('quantity', models.PositiveBigIntegerField(default=0)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
            ],
        ),
    ]
